version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: etl_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ETL_postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: etl_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
  
  grafana:
    image: grafana/grafana
    container_name: etl_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: postgres
      GF_SECURITY_ADMIN_PASSWORD: postgres
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    volumes:
      - ./setup/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./setup/grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  ETL_postgres:
    name: ETL_postgres
    driver: local
