{
 "title": "NYC Traffic Accidents [OLD]",
 "time": { "from": "2011-04-30T11:22:18.000Z", "to": "2026-04-28T11:22:18.000Z" },
 "templating": {
  "list": [
   {
    "name": "time_range",
    "query": "SELECT column_name\nFROM information_schema.columns\nWHERE \n    table_name = 'dim_timestamps' AND \n    table_schema = 'public' AND \n    column_name != 'timestamp_id' AND\n    column_name != 'date_obj'\nORDER BY ordinal_position;"
   }
  ]
 },
 "panels": [
  { "title": "Risk Assessors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Accidents per $time_range",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN '$time_range' = 'hour' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.day AS TEXT), 2, '0') || ' ' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || ':00:00', 'YYYY-MM-DD HH24:MI:SS')\r\n        WHEN '$time_range' = 'day' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0'), 'YYYY-MM-DD')\r\n        WHEN '$time_range' = 'month' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || '-01', 'YYYY-MM-DD')\r\n        WHEN '$time_range' = 'year' THEN to_timestamp(dt.\"$time_range\" || '-01-01', 'YYYY-MM-DD')\r\n    END AS \"time\",\r\n    SUM(fa.n_victims) AS \"Victims\",\r\n    SUM(fa.n_injured) AS \"Injured\",\r\n    SUM(fa.n_killed) AS \"Killed\"\r\nFROM fact_accidents fa\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nGROUP BY CASE\r\n             WHEN '$time_range' = 'hour' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.day AS TEXT), 2, '0') || ' ' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || ':00:00', 'YYYY-MM-DD HH24:MI:SS')\r\n             WHEN '$time_range' = 'day' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0'), 'YYYY-MM-DD')\r\n             WHEN '$time_range' = 'month' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || '-01', 'YYYY-MM-DD')\r\n             WHEN '$time_range' = 'year' THEN to_timestamp(dt.\"$time_range\" || '-01-01', 'YYYY-MM-DD')\r\n         END\r\nORDER BY \"time\" DESC;"
    }
   ]
  },
  {
   "title": "Accidents by ${time_range}",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${time_range}' = 'hour' THEN t.hour\r\n        WHEN '${time_range}' = 'day' THEN t.day\r\n        WHEN '${time_range}' = 'month' THEN t.month\r\n        WHEN '${time_range}' = 'year' THEN t.year\r\n    END AS time_unit,\r\n    COUNT(*) AS \"Accidents Count\"\r\nFROM\r\n    fact_accidents a\r\nJOIN\r\n    dim_timestamps t\r\nON\r\n    a.timestamp_id = t.timestamp_id\r\nWHERE\r\n    t.date_obj BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY\r\n    time_unit\r\nORDER BY\r\n    time_unit;\r\n"
    }
   ]
  },
  {
   "title": "Vehicle Types Involved in Accidents",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH TotalVehicleCount AS (\r\n    SELECT\r\n        COUNT(*) AS total_vehicle_count\r\n    FROM\r\n        fact_accidents a\r\n    JOIN\r\n        dim_vehicles v\r\n    ON\r\n        a.vehicle1_id = v.vehicle_id\r\n        OR a.vehicle2_id = v.vehicle_id\r\n        OR a.vehicle3_id = v.vehicle_id\r\n        OR a.vehicle4_id = v.vehicle_id\r\n        OR a.vehicle5_id = v.vehicle_id\r\n)\r\nSELECT\r\n    v.vehicle_type AS \"Vechicle Type\",\r\n    COUNT(*) AS \"Count\",\r\n    ROUND(\r\n        (COUNT(*)::decimal / (SELECT total_vehicle_count FROM TotalVehicleCount)) * 100,\r\n        2\r\n    ) AS \"Percent\"\r\nFROM\r\n    fact_accidents a\r\nJOIN\r\n    dim_vehicles v\r\nON\r\n    a.vehicle1_id = v.vehicle_id\r\n    OR a.vehicle2_id = v.vehicle_id\r\n    OR a.vehicle3_id = v.vehicle_id\r\n    OR a.vehicle4_id = v.vehicle_id\r\n    OR a.vehicle5_id = v.vehicle_id\r\nGROUP BY\r\n    v.vehicle_type\r\nORDER BY\r\n    \"Count\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Injuries/Killings in relation to Contributing Factors",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    c.contributing_factor AS \"Contributing Factor\",\r\n    SUM(a.n_injured) AS \"Injured\",\r\n    SUM(a.n_killed) AS \"Killed\"\r\nFROM\r\n    fact_accidents a\r\nJOIN\r\n    dim_contributing_factors c\r\nON\r\n    a.contributing_factor1_id = c.contributing_factor_id\r\n    OR a.contributing_factor2_id = c.contributing_factor_id\r\n    OR a.contributing_factor3_id = c.contributing_factor_id\r\n    OR a.contributing_factor4_id = c.contributing_factor_id\r\n    OR a.contributing_factor5_id = c.contributing_factor_id\r\nGROUP BY\r\n    c.contributing_factor;\r\n"
    }
   ]
  },
  {
   "title": "Factors contributing to high-risk scores",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    contributing_factor,\r\n    COUNT(*) AS \"frequency\"\r\nFROM\r\n    fact_accidents\r\n    JOIN dim_contributing_factors ON fact_accidents.contributing_factor1_id = dim_contributing_factors.contributing_factor_id\r\nGROUP BY\r\n    contributing_factor\r\nORDER BY \r\n    \"frequency\" DESC;"
    }
   ]
  },
  { "title": "Geographic Profiling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Geographical heatmaps for highlighting high-risk areas",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dc.latitude, \r\n    dc.longitude, \r\n    COUNT(*) as \"Number of Accidents\"\r\nFROM fact_accidents fa\r\nJOIN dim_coordinates dc ON fa.coordinate_id = dc.coordinates_id\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nWHERE dt.date_obj BETWEEN date_trunc('month', NOW() - INTERVAL '1 month') AND (date_trunc('month', NOW()) - INTERVAL '1 day')\r\nGROUP BY dc.latitude, dc.longitude;"
    }
   ]
  },
  {
   "title": "Injured/Killed by Street",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 14, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    da.on_street_name AS \"On Street\",\r\n    SUM(fa.n_injured) AS \"Injured\",\r\n    SUM(fa.n_killed) AS \"Killed\"\r\nFROM \r\n    fact_accidents fa\r\nJOIN\r\n    dim_addresses da\r\nON \r\n    fa.address_id = da.address_id\r\nWHERE\r\n    da.on_street_name IS NOT NULL\r\n    AND da.on_street_name <> ''\r\nGROUP BY\r\n    da.on_street_name\r\nORDER BY\r\n    \"Injured\" DESC,\r\n    \"Killed\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Injured/Killed by Borough",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    da.borough as \"Borough\", \r\n    SUM(fa.n_injured) AS \"Injured\", \r\n    SUM(fa.n_killed) AS \"Killed\"\r\nFROM \r\n    fact_accidents fa\r\nJOIN \r\n    dim_addresses da \r\nON \r\n    fa.address_id = da.address_id\r\nGROUP BY \r\n    da.borough\r\nORDER BY \r\n    \"Injured\" DESC, \"Killed\" DESC;\r\n"
    }
   ]
  }
 ]
}