version: '3.9'

services:
  grafana:
    image: grafana/grafana
    container_name: etl_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: postgres
      GF_SECURITY_ADMIN_PASSWORD: postgres
      GF_PROVISIONING_PATH: /etc/grafana/provisioning
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
  
  postgres:
    image: postgres:latest
    container_name: etl_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - etl_postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: etl_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
  
  # exporter_postgres:
  #   image: quay.io/prometheuscommunity/postgres-exporter
  #   container_name: etl_exporter_postgres
  #   environment:
  #     DATA_SOURCE_NAME: "postgresql://postgres:postgres@etl_pipeline:5432/?sslmode=disable"
  #   ports:
  #     - "9187:9187"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  etl_postgres:
    name: etl_postgres
    driver: local
