{
 "title": "NYC Traffic Accidents [OLD]",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "time_range",
    "query": "SELECT column_name\nFROM information_schema.columns\nWHERE \n    table_name = 'dim_timestamps' AND \n    table_schema = 'public' AND \n    column_name != 'timestamp_id'\nORDER BY ordinal_position;"
   }
  ]
 },
 "panels": [
  {
   "title": "Claims Department",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Claims Reported today",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n    COUNT(*) \r\nFROM \r\n    fact_accidents \r\nWHERE \r\n    timestamp_id IN (SELECT timestamp_id FROM dim_timestamps WHERE date_obj = CURRENT_DATE - INTERVAL '1 month'); \r\n \r\n "
      }
     ]
    }
   ]
  },
  {
   "title": "Risk Assessors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accidents per $time_range",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT \r\n    CASE\r\n        WHEN '$time_range' = 'hour' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.day AS TEXT), 2, '0') || ' ' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || ':00:00', 'YYYY-MM-DD HH24:MI:SS')\r\n        WHEN '$time_range' = 'day' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0'), 'YYYY-MM-DD')\r\n        WHEN '$time_range' = 'month' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || '-01', 'YYYY-MM-DD')\r\n        WHEN '$time_range' = 'year' THEN to_timestamp(dt.\"$time_range\" || '-01-01', 'YYYY-MM-DD')\r\n    END AS \"time\",\r\n    SUM(fa.n_victims) AS \"Victims\",\r\n    SUM(fa.n_injured) AS \"Injured\",\r\n    SUM(fa.n_killed) AS \"Killed\"\r\nFROM fact_accidents fa\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nGROUP BY CASE\r\n             WHEN '$time_range' = 'hour' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.day AS TEXT), 2, '0') || ' ' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || ':00:00', 'YYYY-MM-DD HH24:MI:SS')\r\n             WHEN '$time_range' = 'day' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.month AS TEXT), 2, '0') || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0'), 'YYYY-MM-DD')\r\n             WHEN '$time_range' = 'month' THEN to_timestamp(dt.year || '-' || LPAD(CAST(dt.\"$time_range\" AS TEXT), 2, '0') || '-01', 'YYYY-MM-DD')\r\n             WHEN '$time_range' = 'year' THEN to_timestamp(dt.\"$time_range\" || '-01-01', 'YYYY-MM-DD')\r\n         END\r\nORDER BY \"time\" DESC;"
      }
     ]
    },
    {
     "title": "Geographical heatmaps for highlighting high-risk areas",
     "type": "geomap",
     "gridPos": { "h": 18, "w": 13, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT \r\n    dc.latitude, \r\n    dc.longitude, \r\n    COUNT(*) as \"Number of Accidents\"\r\nFROM fact_accidents fa\r\nJOIN dim_coordinates dc ON fa.coordinate_id = dc.coordinates_id\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nWHERE dt.date_obj >= NOW() - INTERVAL '1 month'\r\nGROUP BY dc.latitude, dc.longitude;"
      }
     ]
    },
    {
     "title": "Factors contributing to high-risk scores",
     "type": "table",
     "gridPos": { "h": 18, "w": 11, "x": 13, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT\r\n    contributing_factor,\r\n    COUNT(*) AS \"frequency\"\r\nFROM\r\n    fact_accidents\r\n    JOIN dim_contributing_factors ON fact_accidents.contributing_factor1_id = dim_contributing_factors.contributing_factor_id\r\nGROUP BY\r\n    contributing_factor\r\nORDER BY \r\n    \"frequency\" DESC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\r\n    dim_contributing_factors.contributing_factor,\r\n    dim_vehicles.vehicle_type,\r\n    COUNT(*) AS \"number_of_accidents\"\r\nFROM\r\n    fact_accidents\r\nJOIN dim_contributing_factors ON fact_accidents.contributing_factor1_id = dim_contributing_factors.contributing_factor_id\r\nJOIN dim_vehicles ON fact_accidents.vehicle1_id = dim_vehicles.vehicle_id\r\nGROUP BY\r\n    dim_contributing_factors.contributing_factor,\r\n    dim_vehicles.vehicle_type\r\nORDER BY\r\n    \"number_of_accidents\" DESC;"
      }
     ]
    },
    {
     "title": "Total Number of Accidents in the Past Month",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) as total_accidents\r\nFROM fact_accidents fa\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nWHERE dt.date_obj BETWEEN NOW() - INTERVAL '1 MONTH' AND NOW();"
      }
     ]
    },
    {
     "title": "Total Number of Victims in the Past Month",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(n_victims) as total_victims\r\nFROM fact_accidents fa\r\nJOIN dim_timestamps dt ON fa.timestamp_id = dt.timestamp_id\r\nWHERE dt.date_obj BETWEEN NOW() - INTERVAL '1 MONTH' AND NOW();"
      }
     ]
    },
    {
     "title": "Top 10 Contributing factors",
     "type": "barchart",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT dcf.contributing_factor as \"Contributin Factor\", COUNT(*) as \"Count\"\r\nFROM fact_accidents fa\r\nJOIN dim_contributing_factors dcf ON fa.contributing_factor1_id = dcf.contributing_factor_id\r\nGROUP BY dcf.contributing_factor\r\nORDER BY \"Count\" DESC\r\nLIMIT 10;"
      }
     ]
    },
    {
     "title": "Accidets per borrow",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT da.borough, COUNT(*) as number_of_accidents\r\nFROM fact_accidents fa\r\nJOIN dim_addresses da ON fa.address_id = da.address_id\r\nGROUP BY da.borough\r\nORDER BY number_of_accidents DESC;"
      }
     ]
    }
   ]
  }
 ]
}